[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-core>=0.4.7",
    "autogen-ext[azure,grpc,openai]>=0.4.7",
    "fastapi>=0.115.8",
    "rich>=13.9.4",
    "uvicorn>=0.34.0",
]
